name: rfe
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - bottler
  - pyg
  - conda-forge
  - defaults
  - iopath
dependencies:
  - python=3.11
  - pytorch
  - pytorch3d
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pytorch-lightning
  - pytorch-scatter
  - ca-certificates
  - openssl
  - gcc_linux-64
  - gxx_linux-64
  - certifi
  - yacs
  - poetry
  - nvidiacub
  - iopath
  - pyg
  - trimesh
